export const asnaExample = {
  tableHead: ["UNITÉS"],
  tableBody: [
    ["ADMINISTRATION"],
    ["DIRECTION"],
    ["FABRICATION"],
    ["PRODUCTION"],
    ["PROVISOIRE"],
    ["RECRUTEMENT"],
    ["SUPPORT"],
  ],
};

export const tableDatas = {
  tableHead: [
    "Name",
    "Age",
    "Profession",
    "Location",
    "Experience",
    "Salary",
    "Department",
    "Status",
  ],
  tableBody: [
    [
      "Alice",
      "30",
      "Engineer",
      "New York",
      "5 years",
      "$80,000",
      "R&D",
      "Active",
    ],
    [
      "Bob",
      "25",
      "Designer",
      "San Francisco",
      "3 years",
      "$70,000",
      "Marketing",
      "Active",
    ],
    [
      "Charlie",
      "35",
      "Manager",
      "Chicago",
      "10 years",
      "$95,000",
      "HR",
      "Inactive",
    ],
    [
      "David",
      "40",
      "Developer",
      "Boston",
      "15 years",
      "$120,000",
      "IT",
      "Active",
    ],
    [
      "Eva",
      "28",
      "Data Scientist",
      "Los Angeles",
      "4 years",
      "$90,000",
      "Analytics",
      "Active",
    ],
    [
      "Frank",
      "32",
      "Sales Manager",
      "Miami",
      "7 years",
      "$85,000",
      "Sales",
      "Inactive",
    ],
    [
      "Grace",
      "26",
      "UX Designer",
      "Austin",
      "2 years",
      "$75,000",
      "Design",
      "Active",
    ],
    [
      "Henry",
      "29",
      "Software Engineer",
      "Seattle",
      "6 years",
      "$100,000",
      "Engineering",
      "Active",
    ],
    [
      "Irene",
      "31",
      "Product Manager",
      "New York",
      "8 years",
      "$110,000",
      "Product",
      "Active",
    ],
    ["Jack", "27", "QA Tester", "Denver", "3 years", "$65,000", "QA", "Active"],
    [
      "Karen",
      "38",
      "Operations Manager",
      "Phoenix",
      "12 years",
      "$95,000",
      "Operations",
      "Inactive",
    ],
    [
      "Leo",
      "33",
      "Project Manager",
      "Dallas",
      "9 years",
      "$105,000",
      "Projects",
      "Active",
    ],
    [
      "Mia",
      "24",
      "Junior Developer",
      "San Jose",
      "1 year",
      "$60,000",
      "IT",
      "Active",
    ],
    [
      "Nick",
      "36",
      "Business Analyst",
      "New York",
      "11 years",
      "$115,000",
      "Business",
      "Active",
    ],
    [
      "Olivia",
      "30",
      "HR Specialist",
      "Houston",
      "5 years",
      "$80,000",
      "HR",
      "Active",
    ],
    [
      "Paul",
      "34",
      "Tech Lead",
      "Los Angeles",
      "10 years",
      "$125,000",
      "Engineering",
      "Inactive",
    ],
    [
      "Quincy",
      "28",
      "Marketing Coordinator",
      "Atlanta",
      "4 years",
      "$70,000",
      "Marketing",
      "Active",
    ],
    [
      "Rachel",
      "29",
      "DevOps Engineer",
      "Chicago",
      "6 years",
      "$95,000",
      "IT",
      "Active",
    ],
    [
      "Sam",
      "37",
      "Customer Support",
      "Seattle",
      "12 years",
      "$70,000",
      "Support",
      "Active",
    ],
    [
      "Tina",
      "32",
      "Scrum Master",
      "Austin",
      "7 years",
      "$100,000",
      "Agile",
      "Inactive",
    ],
    [
      "Uma",
      "41",
      "Executive Assistant",
      "Boston",
      "16 years",
      "$90,000",
      "Admin",
      "Active",
    ],
    [
      "Victor",
      "35",
      "CTO",
      "New York",
      "15 years",
      "$150,000",
      "Management",
      "Active",
    ],
    [
      "Wendy",
      "30",
      "Data Engineer",
      "San Francisco",
      "6 years",
      "$105,000",
      "Data",
      "Active",
    ],
    [
      "Xander",
      "29",
      "Systems Architect",
      "Los Angeles",
      "7 years",
      "$110,000",
      "IT",
      "Active",
    ],
    [
      "Yara",
      "27",
      "Community Manager",
      "Miami",
      "3 years",
      "$65,000",
      "Marketing",
      "Active",
    ],
  ],
};
